FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS restore
WORKDIR /app

# copy csproj and restore as distinct layers
COPY <%= projectName %>HealthCheckUI.sln .
COPY <%= projectName %>.HealthCheckUI/*.csproj ./<%= projectName %>.HealthCheckUI/
RUN dotnet restore


FROM restore as build
# copy everything else and build app
COPY <%= projectName %>.HealthCheckUI/ ./<%= projectName %>.HealthCheckUI
WORKDIR /app/<%= projectName %>.HealthCheckUI
RUN dotnet publish -c Release -o /app/publish


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "<%= projectName %>.HealthCheckUI.dll"]
