version: '3'

services:
    api:
        build: .
        ports:
        - "5000:80"
        - "5001:443"
        environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    health-check:
        build:
            context: .
            dockerfile: Dockerfile-HealthCheck
        ports:
        - "5050:80"
        - "5051:443"
        links:
        - api:localhost
        environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    # web:
        # build: ./client
        # ports:
        # - "8080:8080"
        # volumes:
        # - ./client/src:/app/src:rw
        # - /app/node_modules
        # environment:
        # - node_env=dev
        # restart: on-failure
        # depends_on:
        # - api