FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS restore
WORKDIR /app

# copy csproj and restore as distinct layers
COPY <%= projectName %>HealthCheckUI.sln .
COPY <%= projectName %>.HealthCheckUI/*.csproj ./<%= projectName %>.HealthCheckUI/
RUN dotnet restore

FROM restore as build
# copy everything else and build app
COPY <%= projectName %>.HealthCheckUI/ ./<%= projectName %>.HealthCheckUI


FROM build as runtime
EXPOSE 5000
EXPOSE 5001
WORKDIR /app/<%= projectName %>.HealthCheckUI
CMD ["dotnet", "watch", "run"]
