FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS restore
WORKDIR /app

# copy csproj and restore as distinct layers
COPY MyProjectHealthCheckUI.sln .
COPY MyProject.HealthCheckUI/*.csproj ./MyProject.HealthCheckUI/
RUN dotnet restore

FROM restore as build
# copy everything else and build app
COPY MyProject.HealthCheckUI/ ./MyProject.HealthCheckUI


FROM build as runtime
EXPOSE 5000
EXPOSE 5001
WORKDIR /app/MyProject.HealthCheckUI
CMD ["dotnet", "watch", "run"]