FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS restore
WORKDIR /app

# copy csproj and restore as distinct layers
COPY MyProjectHealthCheckUI.sln .
COPY MyProject.HealthCheckUI/*.csproj ./MyProject.HealthCheckUI/
RUN dotnet restore


FROM restore as build
# copy everything else and build app
COPY MyProject.HealthCheckUI/ ./MyProject.HealthCheckUI
WORKDIR /app/MyProject.HealthCheckUI
RUN dotnet publish -c Release -o /app/publish


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MyProject.HealthCheckUI.dll"]